name: Notifications-service

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd ./notifications-service && npm install

      - name: Run ESLint
        run: cd ./notifications-service && npm run lint

  jest:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd ./notifications-service && npm install

      - name: Run Jest tests
        run: cd ./notifications-service && npm test

  snyk-scan:
    name: Run Snyk to Check for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: cd ./notifications-service && npm install

      - name: Run Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: cd ./notifications-service && npx snyk test || true

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [eslint, jest, snyk-scan]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.AZURE_REGISTRY_PASSWORD }} | docker login ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io -u ${{ secrets.AZURE_REGISTRY_USERNAME }} --password-stdin

      - name: Build and push Docker image
        env:
          AZURE_REGISTRY_NAME: ${{ secrets.AZURE_REGISTRY_NAME }}
        run: |
          docker buildx build --push --tag ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/notifications:latest --file ./notifications-service/Dockerfile ./notifications-service

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: [build-and-push]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: notificationAppServ
          images: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/notifications:latest
